### ISSUE TITLE
After recording a test the zoom level resets

### ISSUE THREAD

**Issue by ckbedwell** [grafana/k6-studio#218]
### Brief summary

I have an ultra-wide screen so the first thing I did was zoom in so I could see what I was doing in the studio. After recording a test the zoom reset to the default. 

https://github.com/user-attachments/assets/98a2dd99-eec4-40e4-a6f0-6f70c44dcab8

### k6 Studio version

0.1.0

### OS

macOS Sequoia 15.0

### Steps to reproduce the problem

1. Zoom in
2. Record a test
3. See zoom resets after stopping recording

### Expected behaviour

Zoom should stay consistent after stopping the recording.

### Actual behaviour

Zoom seems to change dependent on what state the recording is in and what your last zoom level was. I find differing results dependent on the matrix of what state the recording is in versus what my last and/or current zoom level was/is.

**Comment by e-fisher** [comment]
@ckbedwell I wasn't able to reproduce this - could you verify if it's still reproducible for you in the latest version?

https://github.com/user-attachments/assets/7ad7d4e4-16d6-4067-8e71-2c949817f440

**Comment by going-confetti** [comment]
I can no longer reproduce this in `0.10.0`. If you're still experiencing the problem, please re-open the issue with updated reproduction steps.
