### ISSUE TITLE
WebSocket support

### ISSUE THREAD

**Issue by ppcano** [grafana/k6-studio#241]
### Brief summary

WebSocket requests are converted into k6 http requests

### k6 Studio version

latest

### OS

macOS

### Steps to reproduce the problem

Recording a quickpizza flow https://quickpizza.grafana.com/

### Expected behaviour

Skip WebSocket requests until they are implemented, or alternatively, use the k6 WS API.

### Actual behaviour

Websocket request

![Image](https://github.com/user-attachments/assets/fa25b08b-2363-4d23-8bd5-32333de7ee35)

is converted into k6 http request:

```js
  url = http.url`https://quickpizza.grafana.com/ws`;
    resp = http.request("GET", url, null, params);

    check(resp, {
      "status matches 101": (r) => r.status === 101,
    });
```

it then fails:

![Image](https://github.com/user-attachments/assets/41014d91-2655-46f4-ab60-1fb2c1b1084e)

**Comment by Llandy3d** [comment]
Thanks for reporting this issue!
