### ISSUE TITLE
K6 Studio not running after installation

### ISSUE THREAD

**Issue by bhagatabhijeet** [grafana/k6-studio#345]
### Brief summary

Freshly installed k6 Studio on Windows 10.
i have made sure that dotnet framework 4.5 exists.
the installation seems  like is done as I see the k6 Studio in startmenu
however, after running the k6, the k6 Studio UI never launches.
i have tried running it from the startmentu as well as from the installation directory ~\AppData\Local\k6_studio.exe
i see a bunch of processes  in task manager but the k6 studio UI never launches

### k6 Studio version

0.60

### OS

windows 10

### Steps to reproduce the problem

Freshly installed k6 Studio on Windows 10.
i have made sure that dotnet framework 4.5 exists.
the installation seems  like is done as I see the k6 Studio in startmenu
however, after running the k6, the k6 Studio UI never launches.
i have tried running it from the startmentu as well as from the installation directory ~\AppData\Local\k6_studio.exe
i see a bunch of processes  in task manager but the k6 studio UI never launches

### Expected behaviour

expected to see the k6 Studio UI

### Actual behaviour

k6 studio UI never comes up

**Comment by cristianoventura** [comment]
Hi @bhagatabhijeet, thanks for reporting this issue!

To help us understand the problem and investigate further, could you please:

- attach a tail of k6 Studio log file, which is located in `%USERPROFILE%\AppData\Roaming\k6 Studio\logs\k6-studio.log`
- send a screenshot of your task manager so we can see the list of processes.

**Comment by bhagatabhijeet** [comment]
Sure @cristianoventura  Please find attached the k6-studio.log file and screen shop of task manager
[k6-studio.log](https://github.com/user-attachments/files/17726715/k6-studio.log)
![Image](https://github.com/user-attachments/assets/59a9febd-ab6c-416d-84d1-6ae66c757ae7)

As per the instllation instructions i have chrome browser installed on my system. chrome version Version 130.0.6723.117 (Official Build) (64-bit)

**Comment by fahmeedakaleem** [comment]
I am also facing the same issue as the above person mentioned.

**Comment by Llandy3d** [comment]
This is an interesting issue, seems that it could be related to the gpu 🤔 

Could you please share which GPU you are using and try to either update or reinstall your GPU drivers ?

**Comment by abhagatbb** [comment]
sure @Llandy3d 

- windows Version and Build:

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19044.0 Microsoft Windows NT 10.0.19044.0

here are the pwsh and winver screenshots in one
![Image](https://github.com/user-attachments/assets/b2f37a2f-4771-44af-a165-ecc7e5480b0a)


is k6 Studio installed on the same drive as windows ? --- Yes

**Comment by abhagatbb** [comment]
> Thanks for providing the screenshot and the log file [@bhagatabhijeet](https://github.com/bhagatabhijeet).
> 
> Could you please trying the following steps:
> 
> 1. Kill all instances of k6 Studio in your task manager
> 2. Delete the file JSON file located in `%USERPROFILE%\AppData\Roaming\k6 Studio\k6-studio.json`
> 3. Re-attempt to launch k6 Studio
> 
> If that doesn't work, we can try moving forward by gathering additional information with the steps below.
> 
> It looks like we have two more errors in the log file:
> 
> * A service named `GPU` is being killed. (hence [@Llandy3d](https://github.com/Llandy3d)'s suggestion on upgrading GPU drivers)
> * A service named `network.mojom.NetworkService` is being killed (this one is related to Chromium, probably internal from k6 Studio)
> 
> There seems to be conflicting services that are preventing k6 Studio from launching appropriately. It'd be helpful if you don't mind sharing additional information about your environment:
> 
> * What Windows 10 build are you on?
> * Is k6 Studio installed on the same drive as Windows?

Thank you @cristianoventura  deleting the JSON file JSON file located in %USERPROFILE%\AppData\Roaming\k6 Studio\k6-studio.json and re-launching worked!

i am facing issue like failed to start recording now... i think that can be  logged as a separate issue?

**Comment by bhagatabhijeet** [comment]
sure I **think we can close this issue**.
but before closing just wanted to share an insight.
while i faced the issue... my co worker did not face the issue and thus we verified what could be different on my machine vs her machine 

and the finding is....
she selected  "allow  public networks" on the windows defender dialog.

i did not capture the windows defender actual screenshot but it is something like the one below
![Image](https://github.com/user-attachments/assets/c09e87d0-6c84-43de-ba9f-f38fa9b5c7a0)
