### ISSUE TITLE
Error "Failed To Start Proxy, Restarting..."how to solve this issue

### ISSUE THREAD

**Issue by bhagatabhijeet** [grafana/k6-studio#350]
### Brief summary

I just installed k6 but I'm getting an error message that says "proxy failed to start, restarting." I tried restarting k6 but I'm still getting the same error message. I checked the system log and it just shows following lines

----k6 -studio-log  in ~\AppData\Roaming\k6 Studio\logs
[2024-11-13 23:27:58.082] [error] Error logged during startup, exiting...

[2024-11-13 23:28:03.306] [error] Error logged during startup, exiting...

[2024-11-13 23:28:08.724] [error] Error logged during startup, exiting...

[2024-11-13 23:28:14.296] [error] Error logged during startup, exiting...

-----

### k6 Studio version

0.6

### OS

windows 10 (10.0.19044.0 Microsoft Windows NT 10.0.19044.0)

### Steps to reproduce the problem

1. ensure chrome browser is installed
2. install k6 studio 0.6.0
3. launch k6 studio

### Expected behaviour

k6 is launched

### Actual behaviour

k6 is launched but constantly keep getting following error (error as seen in screenshot)
![Image](https://github.com/user-attachments/assets/c892f5a4-b610-458c-83ba-ad65aff7f0d1)

**Comment by bhagatabhijeet** [comment]
the windows 10 machine stated in this issue is a Virtual Machine (VMWare)

**Comment by cristianoventura** [comment]
@bhagatabhijeet We just released a [new version](https://github.com/grafana/k6-studio/releases/tag/v0.7.0) that includes additional logs for the proxy. You can update to the latest version manually or re-launching k6 Studio (you will be prompted to update).

After that, please re-attach your log file which will then contain additional information.

**Comment by bhagatabhijeet** [comment]
@cristianoventura  Thanks a lot 🙏 i am no longer seeing this issue on the [new version](https://github.com/grafana/k6-studio/releases/tag/v0.7.0)

please allow me to close this issue.
thanks a lot for quick responses.  underneath k6 studio has been created using ElectronJS? i guess i would want to become contributor as and when the opportunity presents/
